CC = gcc
CFLAGS = -c -Wall -g
LFLAGS = -lm
DFLAGS = -pthread 

all: client netfileserver

client: libnetfiles.o 
	$(CC) libnetfiles.o -o client $(LFLAGS)

netfileserver: netfileserver.o
	$(CC) $(DFLAGS) netfileserver.o -o netfileserver $(LFLAGS)

libnetfiles.o: libnetfiles.c
	$(CC) $(CFLAGS) libnetfiles.c

netfileserver.o: netfileserver.c
	$(CC) $(CFLAGS) netfileserver.c

clean:
	rm *o netfileserver client

